# Generated by Django 5.2.4 on 2025-07-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jobopenings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobopenings',
            new_name='JobOpening',
        ),
    ]
