# Generated by Django 5.2.4 on 2025-07-25 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_section_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
